import subprocess
import sys
import os

def run_command(cmd, check=True):
    print(f"Running: {cmd}")
    result = subprocess.run(cmd, shell=True, text=True, capture_output=True)
    if check and result.returncode != 0:
        print(f"Command failed with exit code {result.returncode}")
        print(f"STDOUT: {result.stdout}")
        print(f"STDERR: {result.stderr}")
        sys.exit(result.returncode)
    return result

def main():
    # Ensure GitHub CLI is available
    run_command("gh --version")

    # Configure Git
    run_command('git config user.name "github-actions[bot]"')
    run_command('git config user.email "github-actions[bot]@users.noreply.github.com"')

    print("Running changeset version to consume .md files and update CHANGELOGs...")
    run_command("pnpm changeset version")
    
    status_result = run_command("git status --porcelain")
    status = status_result.stdout.strip()
    
    if not status:
        print("No changesets found or no changes made. Nothing to release.")
        sys.exit(0)
        
    branch_name = "changeset-release/master"

    # Check if the branch already exists remotely
    remote_branches = run_command("git ls-remote --heads origin").stdout.strip()
    if branch_name in remote_branches:
        print(f"Branch {branch_name} already exists. Updating it...")
        run_command(f"git checkout {branch_name}")
        run_command("git reset --hard master")
    else:
        print(f"Creating new branch {branch_name}...")
        run_command(f"git checkout -b {branch_name}")

    # Add and commit the changes
    run_command("git add .")
    run_command('git commit -m "chore(release): version packages"')
    
    # Push the changes
    print("Pushing to remote...")
    run_command(f"git push origin {branch_name} --force")
    
    # Check if a PR already exists
    pr_list_output = run_command(f"gh pr list --head {branch_name} --state open --json number").stdout.strip()
    if pr_list_output == "[]" or '"number"' not in pr_list_output:
        print("Opening new Version Packages PR...")
        pr_body = (
            "This PR was automatically generated by our Python CI pipeline to version packages.\\n\\n"
            "Review the changelog updates and merge when ready to release."
        )
        run_command(f'gh pr create --title "Version Packages" --body "{pr_body}" --base master --head {branch_name}')
    else:
        print("PR already exists. It has been updated with the latest force push.")

    print("Release management complete.")

if __name__ == "__main__":
    main()
