import subprocess
import sys
import os

def run_command(cmd, check=True):
    print(f"Running: {cmd}")
    result = subprocess.run(cmd, shell=True, text=True, capture_output=True)
    if check and result.returncode != 0:
        print(f"Command failed with exit code {result.returncode}")
        print(f"STDOUT: {result.stdout}")
        print(f"STDERR: {result.stderr}")
        sys.exit(result.returncode)
    return result

def main():
    # Ensure GitHub CLI is available
    run_command("gh --version")

    # Configure Git
    run_command('git config user.name "github-actions[bot]"')
    run_command('git config user.email "github-actions[bot]@users.noreply.github.com"')

    branch_name = "changeset-release/master"

    # Position the branch on top of master's current commit *before* running
    # `changeset version`, not after. Doing this the other way around (as
    # this script used to) discards the version-bump changes it's supposed
    # to commit: `git reset --hard master` unconditionally wipes uncommitted
    # working-tree changes, so if it runs *after* `changeset version` has
    # already produced them, they're gone before `git add .` ever sees them
    # -- the commit then fails with "nothing to commit, working tree clean"
    # on every release after the first, i.e. every time this branch already
    # exists from a prior unmerged Version Packages PR. Resetting first also
    # means the branch is always exactly "master + one version-bump commit"
    # after this script runs, instead of accumulating drift across releases.
    remote_branches = run_command("git ls-remote --heads origin").stdout.strip()
    if branch_name in remote_branches:
        print(f"Branch {branch_name} already exists. Resetting it to match master...")
        # actions/checkout only fetches the single ref that triggered the
        # workflow (master here) -- it never fetches other remote branches,
        # even with fetch-depth: 0 (that only removes the depth limit on
        # master's own history). Without this explicit fetch,
        # `git checkout {branch_name}` fails on every release after the
        # first one with "did not match any file(s) known to git", since
        # the local repo has never heard of origin/changeset-release/master.
        run_command(f"git fetch origin {branch_name}")
        run_command(f"git checkout -B {branch_name} origin/{branch_name}")
        run_command("git reset --hard master")
    else:
        print(f"Creating new branch {branch_name}...")
        run_command(f"git checkout -b {branch_name}")

    print("Running changeset version to consume .md files and update CHANGELOGs...")
    run_command("pnpm changeset version")

    status_result = run_command("git status --porcelain")
    status = status_result.stdout.strip()

    if not status:
        print("No changesets found or no changes made. Nothing to release.")
        sys.exit(0)

    # Add and commit the changes
    run_command("git add .")
    run_command('git commit -m "chore(release): version packages"')
    
    # Push the changes
    print("Pushing to remote...")
    run_command(f"git push origin {branch_name} --force")
    
    # Check if a PR already exists
    pr_list_output = run_command(f"gh pr list --head {branch_name} --state open --json number").stdout.strip()
    if pr_list_output == "[]" or '"number"' not in pr_list_output:
        print("Opening new Version Packages PR...")
        pr_body = (
            "This PR was automatically generated by our Python CI pipeline to version packages.\\n\\n"
            "Review the changelog updates and merge when ready to release."
        )
        run_command(f'gh pr create --title "Version Packages" --body "{pr_body}" --base master --head {branch_name}')
    else:
        print("PR already exists. It has been updated with the latest force push.")

    print("Release management complete.")

if __name__ == "__main__":
    main()
