import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { config } from "dotenv";

config({ path: ".env.local" });

const OUTPUT_PATH = "src/contentful/generated/field-unions.generated.ts";
const DOC_PATH = "docs/contentful/constrained-fields.md";
// The CDA strips `in` validations from Symbol fields, so read the CMA instead.
const CMA_BASE_URL = "https://api.contentful.com";

interface ContentfulValidation {
  in?: (string | number)[];
}

interface ContentfulField {
  id: string;
  items?: { validations?: ContentfulValidation[] };
  required?: boolean;
  type: string;
  validations?: ContentfulValidation[];
}

interface ContentfulContentType {
  fields: ContentfulField[];
  sys: { id: string };
}

const pascalCase = (value: string): string =>
  value.charAt(0).toUpperCase() + value.slice(1);

const getAllowedValues = (field: ContentfulField): string[] | undefined => {
  const validations =
    field.type === "Array" ? field.items?.validations : field.validations;
  const allowed = validations?.find((v) => v.in)?.in;
  return allowed?.map(String);
};

interface ConstrainedField {
  allowed: string[];
  contentTypeId: string;
  fieldId: string;
  isArray: boolean;
  required: boolean;
  typeName: string;
}

const buildDoc = (rows: ConstrainedField[]): string => {
  const lines = [
    "<!-- Generated by src/contentful/scripts/generate-field-unions.ts. Do not edit — run `pnpm generate:unions`. -->",
    "",
    "# Constrained Contentful Fields",
    "",
    "Every field whose Contentful validation restricts it to a fixed list of values (`in`), read live from the",
    "Management API. Each row has a matching TypeScript union and `...Values` constant exported from",
    "[`src/contentful/generated/field-unions.generated.ts`](../../src/contentful/generated/field-unions.generated.ts).",
    "See [ADR 0039](../adr/0039-generated-field-unions-from-contentful-validations.md) for why this exists and",
    "[`schema-change-workflow.md`](./schema-change-workflow.md) for how it is kept current.",
    "",
    "| Content type | Field | Kind | Required | TypeScript type | Allowed values |",
    "|---|---|---|---|---|---|",
  ];
  for (const row of rows) {
    const values = row.allowed.map((value) => `\`${value}\``).join(", ");
    lines.push(
      `| \`${row.contentTypeId}\` | \`${row.fieldId}\` | ${row.isArray ? "Array of Symbol" : "Symbol"} | ${row.required ? "Yes" : "No"} | \`${row.typeName}\` | ${values} |`
    );
  }
  return `${lines.join("\n")}\n`;
};

// Only touches a file when its content actually changes, so an unchanged
// content model leaves the working tree (and file watchers) alone.
const writeIfChanged = (path: string, content: string): boolean => {
  if (existsSync(path) && readFileSync(path, "utf8") === content) {
    return false;
  }
  writeFileSync(path, content);
  return true;
};

const buildUnion = (values: string[]): string =>
  values.map((value) => JSON.stringify(value)).join(" | ");

async function main() {
  const spaceId = process.env.CONTENTFUL_SPACE_ID;
  const environmentId = process.env.CONTENTFUL_ENVIRONMENT || "development";
  const managementToken = process.env.CONTENTFUL_MANAGEMENT_TOKEN;

  if (!(spaceId && managementToken)) {
    throw new Error(
      "Missing CONTENTFUL_SPACE_ID or CONTENTFUL_MANAGEMENT_TOKEN"
    );
  }

  const url = `${CMA_BASE_URL}/spaces/${spaceId}/environments/${environmentId}/content_types?limit=1000`;
  const response = await fetch(url, {
    headers: { Authorization: `Bearer ${managementToken}` },
  });

  if (!response.ok) {
    throw new Error(
      `Failed to fetch content types: ${response.status} ${response.statusText}`
    );
  }

  const { items } = (await response.json()) as {
    items: ContentfulContentType[];
  };

  const declarations: string[] = [];
  const rows: ConstrainedField[] = [];

  for (const contentType of items) {
    for (const field of contentType.fields) {
      const allowed = getAllowedValues(field);
      if (!allowed?.length) {
        continue;
      }
      const typeName = `${pascalCase(contentType.sys.id)}${pascalCase(field.id)}`;
      rows.push({
        allowed,
        contentTypeId: contentType.sys.id,
        fieldId: field.id,
        isArray: field.type === "Array",
        required: field.required ?? false,
        typeName,
      });
      declarations.push(
        `export type ${typeName} = ${buildUnion(allowed)};`,
        `export const ${typeName}Values = ${JSON.stringify(allowed)} as const satisfies readonly ${typeName}[];`
      );
    }
  }

  const header =
    "// Generated by src/contentful/scripts/generate-field-unions.ts from Contentful `in` validations. Do not edit.\n";
  const typesChanged = writeIfChanged(
    OUTPUT_PATH,
    `${header}\n${declarations.join("\n")}\n`
  );
  const docChanged = writeIfChanged(DOC_PATH, buildDoc(rows));
  console.log(
    typesChanged || docChanged
      ? `✅ Updated field unions (${rows.length} constrained fields): ${[typesChanged && OUTPUT_PATH, docChanged && DOC_PATH].filter(Boolean).join(", ")}`
      : `⏭  Field unions unchanged (${rows.length} constrained fields)`
  );
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
