import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Layout } from "@components";
import { fetchApplicationData } from "@utils/api";
import { ApplicationDataProvider } from "@context/useApplication";
import "./globals.css";

const inter = Poppins({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Abbas Shaikh | Frontend Developer",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = await fetchApplicationData();
  return (
    <html lang="en" data-theme="dark">
      <body className={inter.className}>
        <ApplicationDataProvider initialData={data}>
          <Layout>{children}</Layout>
        </ApplicationDataProvider>
      </body>
    </html>
  );
}
