import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Container from "@components/Container";
import { fetchCommonCMS } from "@utils/api";
import { DataProvider } from "@context/useInfo";
import "./globals.css";

const inter = Poppins({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Abbas Shaikh | Frontend Developer",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = await fetchCommonCMS();
  return (
    <html lang="en" data-theme="cupcake">
      <body className={inter.className}>
        <DataProvider initialData={data}>
          <Container>{children}</Container>
        </DataProvider>
      </body>
    </html>
  );
}
