import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Layout } from "@components";
import { ApplicationDataProvider } from "@context/useApplication";
import { PAGE_API } from "@utils/data";
import { ApplicationData } from "@utils/contentful";
import "./globals.css";

const inter = Poppins({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Abbas Shaikh | Frontend Developer",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const res = await fetch(
    `${PAGE_API}${process.env.CONTENTFUL_APPLICATION_DATA_ID!}`
  );
  const data: ApplicationData = await res.json();
  console.log(data);
  return (
    <html lang="en" data-theme="dark">
      <body className={inter.className}>
        <ApplicationDataProvider initialData={data}>
          <Layout>{children}</Layout>
        </ApplicationDataProvider>
      </body>
    </html>
  );
}
